name: Release

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Use Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
  release:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Use Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: yarn install
      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
